// frontend/src/components/Sidebar.tsx
/**
 * 侧边栏导航
 * - Logo + 分组菜单 + WS 状态徽章
 * - 折叠态（icon-only）由 useUIStore.sidebarCollapsed 控制
 */
import { NavLink } from 'react-router-dom';
import { useUIStore } from '@/lib/stores/ui';
import { WSStatusIndicator } from './WSStatusIndicator';
import { cn } from '@/lib/utils/cn';

interface NavItem {
  to: string;
  label: string;
  icon: string;
}

interface NavGroup {
  title: string;
  items: NavItem[];
}

const NAV_GROUPS: NavGroup[] = [
  {
    title: '监控',
    items: [
      { to: '/', label: 'Dashboard', icon: '◉' },
      { to: '/gex', label: 'GEX', icon: '◈' },
      { to: '/vix', label: 'VIX', icon: '◈' },
      { to: '/crypto', label: 'Crypto', icon: '◈' },
      { to: '/darkpool', label: 'Dark Pool', icon: '◈' },
    ],
  },
  {
    title: '信号',
    items: [
      { to: '/signals', label: 'Signals', icon: '◈' },
      { to: '/analysis', label: 'Analysis', icon: '◈' },
    ],
  },
  {
    title: '运维',
    items: [
      { to: '/system', label: 'System', icon: '◈' },
      { to: '/settings', label: 'Settings', icon: '◈' },
    ],
  },
];

export function Sidebar() {
  const collapsed = useUIStore((s) => s.sidebarCollapsed);
  return (
    <aside
      className={cn(
        'flex flex-col h-full bg-[var(--color-bg-container)] border-r border-[var(--color-border)] transition-all duration-200',
        collapsed ? 'w-[var(--sidebar-width-collapsed)]' : 'w-[var(--sidebar-width)]',
      )}
      aria-label="主导航"
    >
      {/* Logo */}
      <div className="flex items-center gap-2 px-4 h-[var(--topbar-height)] border-b border-[var(--color-border)]">
        <span className="text-2xl leading-none" aria-hidden>◈</span>
        {!collapsed && <span className="font-semibold tracking-tight">MSR</span>}
      </div>

      {/* Nav groups */}
      <nav className="flex-1 overflow-y-auto py-3">
        {NAV_GROUPS.map((group) => (
          <div key={group.title} className="mb-4">
            {!collapsed && (
              <div className="px-4 text-xs uppercase tracking-wider text-[var(--color-text-muted)] mb-1">
                {group.title}
              </div>
            )}
            <ul className="space-y-0.5">
              {group.items.map((item) => (
                <li key={item.to}>
                  <NavLink
                    to={item.to}
                    end={item.to === '/'}
                    className={({ isActive }) =>
                      cn(
                        'flex items-center gap-3 px-4 py-2 text-sm rounded-r-md mx-1 transition-colors',
                        isActive
                          ? 'bg-[var(--color-primary)]/15 text-[var(--color-primary)] font-medium'
                          : 'text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-elevated)] hover:text-[var(--color-text-primary)]',
                      )
                    }
                    title={collapsed ? item.label : undefined}
                    aria-label={item.label}
                  >
                    <span className="text-base w-5 text-center" aria-hidden>{item.icon}</span>
                    {!collapsed && <span>{item.label}</span>}
                  </NavLink>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </nav>

      {/* Footer: WS status + version */}
      <div className="border-t border-[var(--color-border)] p-3 space-y-2">
        <WSStatusIndicator collapsed={collapsed} />
        {!collapsed && (
          <div className="text-[10px] text-[var(--color-text-muted)] font-mono">v4.0.0</div>
        )}
      </div>
    </aside>
  );
}

// frontend/src/components/layout/Sidebar.vue
<template>
  <aside class="sidebar">
    <div class="sidebar-header">
      <h1 class="logo">MSR</h1>
      <span class="logo-sub">Resonance</span>
    </div>
    <nav class="sidebar-nav">
      <router-link
        v-for="item in navItems"
        :key="item.path"
        :to="item.path"
        class="nav-item"
        :class="{ active: $route.path === item.path }"
      >
        <span class="nav-icon">{{ item.icon }}</span>
        <span class="nav-label">{{ item.label }}</span>
      </router-link>
    </nav>
    <div class="sidebar-footer">
      <div class="version">v3.1</div>
    </div>
  </aside>
</template>

<script setup lang="ts">
const navItems = [
  { path: '/', label: '仪表盘', icon: '◉' },
  { path: '/gex', label: 'GEX', icon: 'Γ' },
  { path: '/vix', label: 'VIX', icon: 'σ' },
  { path: '/crypto', label: '加密', icon: '₿' },
  { path: '/darkpool', label: '暗池', icon: '◈' },
  { path: '/signals', label: '信号', icon: '⚡' },
  { path: '/analysis', label: '分析', icon: '◐' },
  { path: '/system', label: '系统', icon: '⚙' },
  { path: '/settings', label: '配置', icon: '☰' },
]
</script>

<style scoped>
.sidebar {
  width: var(--sidebar-width);
  background: var(--bg-secondary);
  border-right: 1px solid var(--glass-border);
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  height: 100vh;
}
.sidebar-header {
  padding: var(--spacing-lg);
  border-bottom: 1px solid var(--glass-border);
  display: flex;
  align-items: baseline;
  gap: 8px;
}
.logo {
  font-size: 22px;
  font-weight: 800;
  color: var(--accent-indigo);
  letter-spacing: 2px;
}
.logo-sub {
  font-size: 12px;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 1px;
}
.sidebar-nav {
  flex: 1;
  padding: var(--spacing-sm) 0;
  overflow-y: auto;
}
.nav-item {
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  padding: 10px var(--spacing-lg);
  color: var(--text-secondary);
  text-decoration: none;
  font-size: 14px;
  transition: all 0.2s;
  border-left: 3px solid transparent;
}
.nav-item:hover {
  background: var(--glass-bg);
  color: var(--text-primary);
}
.nav-item.active {
  background: rgba(99, 102, 241, 0.1);
  color: var(--accent-indigo);
  border-left-color: var(--accent-indigo);
}
.nav-icon {
  font-size: 16px;
  width: 24px;
  text-align: center;
}
.sidebar-footer {
  padding: var(--spacing-md) var(--spacing-lg);
  border-top: 1px solid var(--glass-border);
}
.version {
  font-size: 11px;
  color: var(--text-muted);
}
</style>
